@startuml
start
    note left
        host 1
    end note
fork
:instantiate discovery_thread from DiscoveryThread;
:enter multicast group;
repeat
    :send multicast message;
    note left
        sent to all hosts
    end note
    :update hosts;
    :emit hosts_updated signal;
    note left
        updates GUI
    end note
repeat while (discovery_thread still runnung) is (true)
fork again
    :instantiate server_thread from ServerThread;
    :start HTTPS server;
    repeat
        :wait for connection to route "/connect";
        :add remote host to known hosts;
repeat while (server_thread still running) is (true)

end fork
    note right
  Both discovery_thread
  and server_thread
  process the
  "hosts" dictionary
end note
stop
@enduml